version: '3'
services:
  backend:
    container_name: bergflix-backend
    build:
      context: ./backend
      target: production
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - bergflix
      - proxy
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: bergflix-db
    restart: unless-stopped
    networks:
      - bergflix
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data

  frontend:
    container_name: bergflix-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_PATH=https://api.bf.acrys.gg
    networks:
      - proxy

networks:
  bergflix:
    name: bergflix
  proxy:
    name: proxy
