version: '3'
services:
  backend:
    container_name: bergflix-backend
    build:
      context: ./backend
      target: development
      dockerfile: ./Dockerfile
    command: yarn run start:debug
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - bergflix
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: bergflix-db
    networks:
      - bergflix
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  bergflix:
    name: bergflix
